# compare two model using F-test
model1: $y(t) = ky(t-h) + x(t)\beta + \epsilon$ 

model2: $y(t) = ky(t-h) + \epsilon$

In [1]:
import pickle
from pathlib import Path
import os
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
from scipy import stats
import pandas as pd

os.chdir("/work")

DATA_ROOT = Path('data/alldata/')
OUTPUT_ROOT = Path("output/")

datalist = np.array([x for x in DATA_ROOT.iterdir()])
output_dir = OUTPUT_ROOT/"ridge_regression/"

In [4]:
def get_RSS(results_all: list, nthist: int, axis: str):
    """Get RSS and degree of freedom."""
    filtered_result = [result for result in results_all if (result["nthist"]==nthist)and(result["coord_axis"]==axis)][0]
    rss = filtered_result['sig_tests'].RSS
    df = filtered_result['sig_tests'].df_model
    return rss, df

def cal_f_stat(rss1, rss2, df1, df2):
    """Cal the F statistics and corresponding p-value."""
    tmp1 = (rss2 - rss1)/df2
    tmp2 = rss1/df1
    f_stat = tmp1/tmp2
    return f_stat, stats.f.sf(f_stat, df2, df1)

def gen_df(data_dir):
    data_name = str(data_dir).split('/')[-1]
    mouse_type = "knockout" if "CaMKII" in data_name else "wild-type"
    print(mouse_type)

    # spikes+ past coord
    with open(output_dir/(f"rr_spikes_past_coord_eval_{data_name}.pickle"),"rb") as f:
        sp_results_all = pickle.load(f)
    # only past-coord
    with open(output_dir/(f"rr_only_past_coord_eval_{data_name}.pickle"),"rb") as f:
        op_results_all = pickle.load(f)

    f_p_list = []
    f_stat_list = []
    for nthist in np.arange(1,30):
        axis = "x-axis"
        rss1, df1 = get_RSS(sp_results_all ,nthist, axis)
        rss2, df2 = get_RSS(op_results_all ,nthist, axis)
        f_stat, f_p_value = cal_f_stat(rss1, rss2, df1, df2)
        f_p_list.append(f_p_value)
        f_stat_list.append(round(f_stat, 2))
    df = pd.DataFrame({
        "num of history time bins": np.arange(1,30),
        "F test p value": f_p_list,
        "F statistics": f_stat_list
        })
    return df

## wild-type mice

In [8]:
data_dir = datalist[4]
gen_df(data_dir)

wild-type

    num of history time bins  F test p value  F statistics
0                          1        0.000005          1.20
1                          2        0.000005          1.20
2                          3        0.918198          0.95
3                          4        0.983350          0.93
4                          5        0.996232          0.91
5                          6        1.000000          0.34
6                          7        0.006796          1.11
7                          8        1.000000          0.34
8                          9        0.010754          1.10
9                         10        1.000000          0.33
10                        11        0.999944          0.87
11                        12        0.999968          0.87
12                        13        1.000000          0.09
13                        14        0.999977          0.87
14                        15        0.999990          0.86
15                        16        1.000000          0.76
16                        17        1.000000          0.76
17                        18        0.017176          1.09
18                        19        1.000000          0.77
19                        20        0.026065          1.08
20                        21        0.999998          0.78
21                        22        0.999996          0.79
22                        23        1.000000          0.79
23                        24        0.999984          0.80
24                        25        0.042294          1.07
25                        26        0.999953          0.81
26                        27        0.063197          1.07
27                        28        0.059937          1.07
28                        29        1.000000          0.75

## knockout

In [9]:
data_dir = datalist[0]
gen_df(data_dir)

knockout

    num of history time bins  F test p value  F statistics
0                          1        1.000000          0.24
1                          2        1.000000          0.25
2                          3        1.000000          0.60
3                          4        1.000000          0.60
4                          5        1.000000          0.61
5                          6        1.000000          0.27
6                          7        1.000000          0.64
7                          8        1.000000          0.56
8                          9        1.000000          0.29
9                         10        1.000000          0.57
10                        11        1.000000          0.30
11                        12        1.000000          0.30
12                        13        1.000000          0.58
13                        14        1.000000          0.72
14                        15        1.000000          0.33
15                        16        1.000000          0.75
16                        17        1.000000          0.77
17                        18        1.000000          0.04
18                        19        1.000000          0.04
19                        20        1.000000          0.36
20                        21        1.000000          0.04
21                        22        1.000000          0.38
22                        23        1.000000          0.04
23                        24        1.000000          0.04
24                        25        1.000000          0.04
25                        26        1.000000          0.04
26                        27        0.977044          0.90
27                        28        1.000000          0.04
28                        29        1.000000          0.04